# Generated by Django 2.0.5 on 2018-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(blank=True, max_length=512, verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
    ]
